# Generated by Django 2.1 on 2018-08-01 18:17

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('', '-----'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.')], max_length=5)),
                ('first', models.CharField(max_length=40)),
                ('middle', models.CharField(max_length=1)),
                ('last', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=20)),
                ('cos_ptid', models.IntegerField()),
                ('location', models.CharField(choices=[('BV', 'BV'), ('WD', 'WD'), ('PA', 'PA')], max_length=5)),
                ('address', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip', localflavor.us.models.USZipCodeField(max_length=10)),
                ('home_phone', models.CharField(blank=True, help_text='10 digits max, no dashes', max_length=10)),
                ('work_phone', models.CharField(blank=True, help_text='10 digits max, no dashes', max_length=10)),
                ('cell_phone', models.CharField(blank=True, help_text='10 digits max, no dashes', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('SSN', localflavor.us.models.USSocialSecurityNumberField(max_length=11)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=5)),
                ('student', models.BinaryField()),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('alert', models.CharField(blank=True, max_length=100)),
                ('outside_doc', models.CharField(max_length=50)),
                ('referred_to_doc', models.CharField(max_length=50)),
            ],
        ),
    ]
