# Generated by Django 2.1 on 2018-08-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='student',
            field=models.BooleanField(),
        ),
    ]
