# Generated by Django 2.1 on 2018-08-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20180803_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nickname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='work_phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
