# Generated by Django 2.1 on 2018-08-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20180803_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Lens_Rx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('expires', models.DateField()),
                ('doctor', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=256)),
                ('od_base_curve', models.IntegerField()),
                ('od_power', models.IntegerField()),
                ('od_power2', models.IntegerField()),
                ('od_ax', models.IntegerField()),
                ('od_diam', models.IntegerField()),
                ('od_add', models.IntegerField()),
                ('os_base_curve', models.IntegerField()),
                ('os_power', models.IntegerField()),
                ('os_power2', models.IntegerField()),
                ('os_ax', models.IntegerField()),
                ('os_diam', models.IntegerField()),
                ('os_add', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spectacle_Rx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('expires', models.DateField()),
                ('doctor', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=256)),
                ('od_sphere', models.IntegerField()),
                ('od_cylinder', models.IntegerField()),
                ('od_axis', models.IntegerField()),
                ('od_prism', models.IntegerField()),
                ('od_prism2', models.IntegerField()),
                ('od_add', models.IntegerField()),
                ('os_sphere', models.IntegerField()),
                ('os_cylinder', models.IntegerField()),
                ('os_axis', models.IntegerField()),
                ('os_prism', models.IntegerField()),
                ('os_prism2', models.IntegerField()),
                ('os_add', models.IntegerField()),
                ('sv_reading', models.BooleanField()),
                ('sv_distance', models.BooleanField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
