# Generated by Django 2.1 on 2018-08-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('patients', '0005_contact_lens_rx_spectacle_rx'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_lens_rx',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_patients.contact_lens_rx_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='spectacle_rx',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_patients.spectacle_rx_set+', to='contenttypes.ContentType'),
        ),
    ]
