# Generated by Django 2.1 on 2018-08-06 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('patients', '0006_auto_20180806_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common_Rx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('expires', models.DateField()),
                ('doctor', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=256)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_patients.common_rx_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AlterModelOptions(
            name='contact_lens_rx',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='spectacle_rx',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='contact_lens_rx',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='contact_lens_rx',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='contact_lens_rx',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='contact_lens_rx',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contact_lens_rx',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='contact_lens_rx',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='contact_lens_rx',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='spectacle_rx',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='spectacle_rx',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='spectacle_rx',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='spectacle_rx',
            name='id',
        ),
        migrations.RemoveField(
            model_name='spectacle_rx',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='spectacle_rx',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='spectacle_rx',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='contact_lens_rx',
            name='common_rx_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patients.Common_Rx'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spectacle_rx',
            name='common_rx_ptr',
            field=models.OneToOneField(auto_created=True, default=1234, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patients.Common_Rx'),
            preserve_default=False,
        ),
    ]
