# Generated by Django 2.1 on 2018-08-10 16:45

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('patients', '0007_auto_20180806_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('relation_to_insured', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('child', 'Child'), ('other', 'Other')], max_length=20)),
                ('bill_payer', models.CharField(max_length=30)),
                ('bp_address1', models.CharField(max_length=40)),
                ('bp_address2', models.CharField(blank=True, max_length=40)),
                ('bp_city', models.CharField(max_length=40)),
                ('bp_state', localflavor.us.models.USStateField(max_length=2)),
                ('bp_zip', localflavor.us.models.USZipCodeField(max_length=10)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Medical_Ins',
            fields=[
                ('patient_insurance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patients.Patient_Insurance')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('patients.patient_insurance',),
        ),
        migrations.CreateModel(
            name='Vision_Ins',
            fields=[
                ('patient_insurance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='patients.Patient_Insurance')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('patients.patient_insurance',),
        ),
        migrations.AddField(
            model_name='patient_insurance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='patient_insurance',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_patients.patient_insurance_set+', to='contenttypes.ContentType'),
        ),
    ]
