# Generated by Django 2.1 on 2018-08-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20180810_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_ins',
            name='company_name',
            field=models.CharField(choices=[('Temp Medical', 'Temp Medical')], default='Geico', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vision_ins',
            name='company_name',
            field=models.CharField(choices=[('Temp Vision', 'Temp Vision')], default='Geico', max_length=30),
            preserve_default=False,
        ),
    ]
