# Generated by Django 2.1 on 2018-08-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20180810_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='common_rx',
            options={'verbose_name_plural': "Common Rx's"},
        ),
        migrations.AlterModelOptions(
            name='medical_ins',
            options={'verbose_name_plural': 'Medical Insurances'},
        ),
        migrations.AlterModelOptions(
            name='patient_insurance',
            options={'verbose_name_plural': 'Patient Insurances'},
        ),
        migrations.AlterModelOptions(
            name='spectacle_rx',
            options={'verbose_name_plural': "Spectacle Rx's"},
        ),
        migrations.AlterModelOptions(
            name='vision_ins',
            options={'verbose_name_plural': 'Vision Insurances'},
        ),
        migrations.AddField(
            model_name='patient_insurance',
            name='plan_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
