# Generated by Django 2.1 on 2018-08-01 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('BV', 'BV'), ('WD', 'WD'), ('PA', 'PA')], max_length=5)),
                ('comments', models.CharField(max_length=264)),
                ('date_added', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('vendor', models.CharField(max_length=30)),
                ('comments', models.CharField(max_length=264)),
                ('style', models.CharField(choices=[('M', "Men's"), ('W', "Women's")], default=True, max_length=5)),
                ('desc', models.CharField(max_length=30)),
                ('sku', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.CharField(default='BLACK', max_length=30)),
                ('VID', models.IntegerField(default=1753674)),
                ('HCFA', models.CharField(default='V2020', max_length=30)),
                ('wholesale', models.FloatField()),
                ('retail', models.FloatField()),
                ('cost', models.FloatField()),
                ('taxable', models.BooleanField()),
                ('on_hand', models.IntegerField()),
                ('on_order', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField()),
                ('lead_time', models.IntegerField()),
                ('eye', models.IntegerField()),
                ('bridge', models.IntegerField()),
                ('temple', models.IntegerField()),
                ('A', models.IntegerField()),
                ('B', models.IntegerField()),
                ('ED', models.IntegerField()),
                ('DBL', models.IntegerField()),
                ('sold_this_week', models.IntegerField(default=0)),
                ('sold_this_month', models.IntegerField(default=0)),
                ('sold_this_year', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='pair',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Type'),
        ),
    ]
