# Generated by Django 2.1 on 2018-08-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='comments',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
