# Generated by Django 2.1 on 2018-08-10 16:49

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('medical', 'medical'), ('vision', 'vision')], max_length=30)),
                ('active', models.BooleanField()),
                ('plan_name', models.CharField(max_length=30)),
                ('address1', models.CharField(max_length=40)),
                ('address2', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip', localflavor.us.models.USZipCodeField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('fax_number', models.CharField(blank=True, max_length=20)),
                ('contact_person', models.CharField(max_length=40)),
                ('notes', models.CharField(max_length=250)),
            ],
        ),
    ]
