# Generated by Django 2.1 on 2018-08-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='company_name',
            field=models.CharField(default='Geico', max_length=30),
            preserve_default=False,
        ),
    ]
