# Generated by Django 2.1 on 2018-08-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_insurance_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='notes',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
